### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by eyadsibai** [pyhunspell/pyhunspell#40]
hunspell is available thru conda `conda install -c confa-forge hunspell` it would be nice to install pyhunspell using conda too

**Comment by blatinier** [comment]
I'm not an conda user and I don't really want to add another stuff to maintain for me. However if you really are interested in adding it to conda you can do it and I could answer your questions if you have any.

Procedure is here: https://conda-forge.org/#add_recipe

**Comment by eyadsibai** [comment]
I understand, but your package is not available as wheel too. I am sure you will have so many issues about installing the package. For example I did install libhunspell-div and still have some issues installing your package, but if your package is available to be installed easily. Less issues and definitely will get more publicity.

**Comment by eyadsibai** [comment]
Look at the no. of issues you have (closed+open) regarding installation issues. compared to the total number of issues

**Comment by blatinier** [comment]
Ok so I checked about wheel and I can't provide any since it's not allowed to push Linux wheels on pypi (Linux variations are to tricky), and I don't own any Mac nor Windows.
However I made the necessary changes for a wheel to be made (master updated a few minutes ago).
I am also digging into conda, I'll comment here when my PR to conda-recipes is available. We will see if it's a lot of work to maintain in the future.

**Comment by blatinier** [comment]
Here is my PR (work in progress):
https://github.com/conda-forge/staged-recipes/pull/5071

**Comment by blatinier** [comment]
Ok I'm stuck on this. I don't know how to setup the build env that my package require on conda (install libhunspell-dev and the install of hunspell seems broken too...). And much more I have no idea how I could do it. @eyadsibai if you have some experience with conda recipes feel free to help on it. (For now the style check pass, nothing else... https://github.com/conda-forge/staged-recipes/pull/5071)
